### PR TITLE
Fix capitalization of labels & column name in Github actions

### PR DESCRIPTION
**Pull request by starryeyez024**
## Infrastructure updates

- Updated label names (lowercase) within the github automation tasks 
- Adjusted column name from "Needs discovery" to "backlog" in workflow

### Testing instructions

I'm not certain if you can test workflows before merging?

### Ready-for-merge Checklist

Check off items as they are completed.  Feel free to delete items if they are not applicable to your PR.

- [x] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [x] Repository compiles and tests pass.
- [x] Changelog updated. 

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by castastrophe** [comment]
@starryeyez024 Don't forget the issue and pull request templates too please.

**Comment by castastrophe** [comment]
Re-bumping this feedback and adding back the `needs updates` label:
> @starryeyez024 Don't forget the issue and pull request templates too please.

**Comment by starryeyez024** [comment]
@castastrophe sorry I thought you meant, "use a PR template for this PR, 944", but now I understand you mean I should edit the templates in the .github directory of the project. Will the labels with colons cause issues with the syntax of the template? Should those become dashes instead?
image

**Comment by castastrophe** [comment]
> Will the labels with colons cause issues with the syntax of the template? Should those become dashes instead?
> image

You can quote the labels that include colons in the templates.  I found this PR as an example: https://github.com/celery/celery/pull/5955/files

> Separate question, should the templates auto-assign priority labels? We can't know how important a thing is until we review it against other requests & priorities.

I think it makes sense to auto-assign a low priority to all PRs and require it be escalated.  Note that each template includes instructions at the bottom about the priority levels (if these have been renamed those comments should be updated as well).

**Comment by starryeyez024** [comment]
> I think it makes sense to auto-assign a low priority to all PRs and require it be escalated. Note that each template includes instructions at the bottom about the priority levels (if these have been renamed those comments should be updated as well).
> 

I agree; I was mistakenly read "sev-1" as high priority again which was my main concern. But since that means low, I'm ok with that approach. I updated the templates as such. 

Just one point of clarification; in your comment above you mention using priority levels on the PRs, however in the existing templates, the priority labels were only used on the issue templates (not PRs). I followed suite and just updated the label names but left priority off the PR templates.

**Pull request merged**
