### PR TITLE
fix(tools): dev server icon and colours

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. change dev server header colour to black
2. use correct url for dev server header icon

### CODE REVIEW

**Review by zeroedin — CHANGES_REQUESTED** [review]
Having issues running dev server on this branch:

```
Now using node v20.10.0 (npm v10.2.3)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @patternfly/pfe-tools@2.0.0
npm ERR! Found: esbuild@0.20.2
npm ERR! node_modules/esbuild
npm ERR!   esbuild@"^0.20.2" from @patternfly/pfe-tools@2.0.0
npm ERR!   tools/pfe-tools
npm ERR!     @patternfly/pfe-tools@2.0.0
npm ERR!     node_modules/@patternfly/pfe-tools
npm ERR!       workspace tools/pfe-tools from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.16.17 || ^0.17.16 || ^0.18.1 || ^0.19.5" from esbuild-plugin-lit-css@2.1.0
npm ERR! node_modules/esbuild-plugin-lit-css
npm ERR!   esbuild-plugin-lit-css@"^2.1.0" from @patternfly/pfe-tools@2.0.0
npm ERR!   tools/pfe-tools
npm ERR!     @patternfly/pfe-tools@2.0.0
npm ERR!     node_modules/@patternfly/pfe-tools
npm ERR!       workspace tools/pfe-tools from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

If I upgrade the following deps in `tools/pfe-tools/package.json` to:

```
    "esbuild-plugin-lit-css": "^3.0.0",
    "esbuild-plugin-minify-html-literals": "^2.0.0",
```

And remove the following comment `@ts-expect-error`
```
❌ [build:tools] exited with exit code 1. Output:

tools/pfe-tools/dev-server/config.ts:19:1 - error TS2578: Unused '@ts-expect-error' directive.

19 // @ts-expect-error: looks like this was broken upstream. remove this expect-error directive when they fix it
   
```

things work.  If this matches expectations let me know I'll push this as a commit.

**Comment by bennypowers** [comment]
@zeroedin please do

**Review by zeroedin — APPROVED** [review]
Logo good, to merge ➡️

**Comment by zeroedin** [comment]
unexpected test failures.  taking a look.

**Pull request merged**
