### PR TITLE
Version Packages (next)

### PR DESCRIPTION
**Pull request by bennypowers**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

⚠️⚠️⚠️⚠️⚠️⚠️

`main` is currently in **pre mode** so this branch has prereleases rather than normal releases. If you want to exit prereleases, run `changeset pre exit` on `main`.

⚠️⚠️⚠️⚠️⚠️⚠️

# Releases
### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

 ## @patternfly/pfe-sass@2.0.0-next.5

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

 ## @patternfly/pfe-accordion@2.0.0-next.4

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   Updated dependencies [6a2a0407]
-   Updated dependencies [0e9a4130]
    -   @patternfly/pfe-core@2.0.0-next.4
    -   @patternfly/pfe-collapse@2.0.0-next.2
    -   @patternfly/pfe-icon@2.0.0-next.2

 ## @patternfly/pfe-band@2.0.0-next.2

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-card@2.0.0-next.3

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-cta@2.0.0-next.3

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   f66ba580: Add color context support via explicitly defined attributes. See <https://github.com/patternfly/patternfly-elements/pull/1976>
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-jump-links@2.0.0-next.3

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4
    -   @patternfly/pfe-accordion@2.0.0-next.4

 ## @patternfly/pfe-modal@2.0.0-next.2

### Major Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-styles@2.0.0-next.2

### Minor Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

 ## @patternfly/pfe-collapse@2.0.0-next.2

### Minor Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)

### Patch Changes

-   0e9a4130: Export `pfe-collapse-panel.js` from package.json
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-tools@1.0.0-next.16

### Minor Changes

-   bb5b6265: Add `additionalPackages` option to `singleFileBundle`
-   effe009a: Adds a maximize toggle to the dev SPA

### Patch Changes

-   4997735b: update dependencies

 ## @patternfly/pfe-button@2.0.0-next.3

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-clipboard@2.0.0-next.3

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   6883aa36: pfe-clipboard: add fallback check for http traffic on browsers that support navigator.
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-datetime@2.0.0-next.3

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-dropdown@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-health-index@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-icon@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-icon-panel@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4
    -   @patternfly/pfe-icon@2.0.0-next.2

 ## @patternfly/pfe-label@1.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4
    -   @patternfly/pfe-icon@2.0.0-next.2

 ## @patternfly/pfe-markdown@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-number@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-page-status@2.0.0-next.3

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-progress-indicator@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-readtime@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-select@2.0.0-next.3

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-tabs@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

 ## @patternfly/pfe-toast@2.0.0-next.2

### Patch Changes

-   6a2a0407: [View commit message here](https://gist.github.com/heyMP/200fc0b840690541475923facba393ab)
-   Updated dependencies [6a2a0407]
    -   @patternfly/pfe-core@2.0.0-next.4

### CODE REVIEW

**Comment by bennypowers** [comment]
@heyMP The problem here was changesets action generating a PR description message that was too long by about 10000 chars. See https://github.com/changesets/action/issues/174

My solve was to manually open a PR from `changesets-release/main` to `main` with a manually edited PR body. That PR body won't affect the changelog files.

This PR will merge, triggering a release, upon approval

cc @zeroedin @brianferry

**Comment by bennypowers** [comment]
@patternfly/patternfly-elements-maintainers NB:

The [netlify deploy preview failed with `NPM ERR! code ETARGET`](https://app.netlify.com/sites/patternfly-elements/deploys/625bd4be196b7736eebce9fe). This is an important safeguard against broken release branches. When this happens, first try "Clear cache and retry deploy" on the Netlify UI, then if that fails, you can re-synchronize the package-lock by checking out the release branch:

```bash
git checkout main
git fetch
git checkout changeset-release/main
git pull
```

Then clearing any installed node_modules and resetting the package-lock
```bash
rm -rf node_modules
rm -rf ./**/node_modules
rm package-lock.json
npm i
```

at that point you _should_ see unstaged changes in `package-lock.json` (if not, something went really screwy). Just commit those changes to this branch and it should clear the issue:

```bash
git add package-lock.json
git commit --message "chore: fix package lock"
git push
```

**Comment by bennypowers** [comment]
**DO NOT MERGE** before #2001 merges and this PR is updated in CI

**Comment by bennypowers** [comment]
Land's green, tread mares!

**Review by heyMP — APPROVED** [review]

**Pull request merged**
