### PR TITLE
fix(tabs): make showOverflow protected

### PR DESCRIPTION
**Pull request by zeroedin**
## What I did

1. Made `showScrollButtons` protected in order to be able to read it from a child class.

## Notes:  

By making `showScrollButtons` protected I can read it in a child class downstream. This will allow the child class to know if the overflow has occurred or not.

### CODE REVIEW

**Review by bennypowers — COMMENTED** [review]
Rather than loading this onto the base class, can it go on the container in the implementing class?

**Comment by bennypowers** [comment]
Maybe we can move that logic into a controller and make the controller an implementation concern in *-tabs

**Comment by zeroedin** [comment]
> Rather than loading this onto the base class, can it go on the container in the implementing class?

I would definitely like to do this elsewhere.  Wasn't ideal doing this here, rather the first idea that came to mind. The other thought that was maybe more appropriate was making `this.#showScrollButtons` publically readable, and reading the value to set the class in RHDS instead.

**Comment by zeroedin** [comment]
> 



> Maybe we can move that logic into a controller and make the controller an implementation concern in *-tabs

Quite possible.  Going to see what the design specs say.  There is a possibility to need a container query controller as well to dictate what spacing is needed and at what size of the container, not just if the container is overflowed or not.  At that point, then it is a bigger change than what this draft PR is currently reflecting.

**Comment by zeroedin** [comment]
Closed superseded by: https://github.com/patternfly/patternfly-elements/pull/2375

**Pull request closed without merging**
