### PR TITLE
adding a version getter to each component

### LINKED ISSUE #428: Add the release version in the compiled JavaScript
Ideally the compiled JavaScript files for each web component should contain the version release number as a part of the Lerna packaging build steps. 

This is fairly necessary (esp. for redhat.com) since the JS is packaged up by webrh, and shipped through drupal, which then bundles it up via AdvAgg. Even after you dig through aggregated files to look for the pfe-cta.js, you can't tell which version it is, which makes it very difficult to debug or know if something is still a real issue.

### PR DESCRIPTION
**Pull request by kylebuch8**
Reads the version in the package.json file and adds it as a getter during the build process

Fixes #428

### CODE REVIEW

**Comment by starryeyez024** [comment]
@kylebuch8 Thank you for creating this PR! I need testing instructions please :)

**Comment by kylebuch8** [comment]
@starryeyez024 - In any component, in the `constructor`, `connectedCallback`, or any function really, run `console.log(this.version);`

If you're using the global version (not require or es6 version) and PFElement is available on the window object, going to the console in the developer tools and typing `PFElement.version` should give you what you're looking for.

**Comment by castastrophe** [comment]
@kylebuch8 This is cool but I think the original ask was to include a comment with the version info in the compiled js files.  This would still be the most valuable place for that information as that is where we run into the most issues confirming what version we fetched from npm.

**Comment by mwcz** [comment]
It should be a really easy to change to this PR to add that, just a `${version}` in the license comment should do the trick.

**Comment by mwcz** [comment]
I took a stab at this so we can finish off this PR.  It wasn't _quite_ as easy as I thought but it wasn't too bad.

The license comments now look like this:

**pfelement.js**
```js
/*!
 * PFElement 1.0.0-prerelease.17
 * @license
 * Copyright 2019 Red Hat, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy... etc
```
**pfe-card.js**
```js
/*!
 * PfeCard 1.0.0-prerelease.17
 * @license
 * Copyright 2019 Red Hat, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy... etc

```

**Comment by starryeyez024** [comment]
@mwcz when I run `npm run dev pfe-card` or `npm run build` the pfe-card.js file does not include the version number. Is there a way to also include the info during these build tasks so that we can verify that files we are working on, compile, copy into some other system like drupal and sync to sandboxes are indeed the expected files?

**Comment by mwcz** [comment]
@starryeyez024 

Question 1: are you sure you're on the right branch?

```
$ npm run build pfe-card
$ head elements/pfe-card/pfe-card.js
import PFElement from '../pfelement/pfelement.js';

/*!
 * PatternFly Elements: PfeCard 1.0.0-prerelease.17
 * @license
 * Copyright 2019 Red Hat, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
```

Question 2: I don't understand this question, could you phrase it another way for me?  What is "the info"?

**Comment by starryeyez024** [comment]
Hooray! with the latest commits, this works great.

Leftovers: Grilled Tomato & Mozzarella

**Pull request merged**
