### PR TITLE
fix(core)!: add getItems and getItemsContainer to RTI constructor

### LINKED ISSUE #2644: Allow `items` and `itemsContainer` to be lazily added to the `roving-tabindex-controller`
## Allow `items` and `itemsContainer` to be lazily added to the `roving-tabindex-controller`

From notes with Benny:

- Hosts could provide a functions for getting  `items` and `itemsContainer`
- Mutation observer could watch for changes to update items and container
- Public `initItems` could be deprecated

See: https://github.com/patternfly/patternfly-elements/pull/2570/files#r1359803876

### Impacted component(s)
- `pf-accordion`
- `pf-chip`
- `pf-tabs`
- `pf-select`
- `rh-accordion`
- `rh-audio-player`
- `rh-navigation-secondary`
- `rh-tabs`
- `rh-tile`

## Related issues

- #2570

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #2644

## What I did

1. add `getItems` and `getItemContainer` option functions to RTIC, update call sites
2. make `updateItems` parameter default to the result of `getItems`

## Testing Instructions

1. units, manual keyboard testing for rti elements

### CODE REVIEW

**Review by zeroedin — COMMENTED** [review]
image

Tabs aren't loading correctly with change to RTI initialization.  Going to dig into this a bit further to look for a fix.

**Comment by bennypowers** [comment]
@zeroedin merged in the linked branch, PTAL

**Comment by zeroedin** [comment]
> That branch was never merged into main now so those changes were lost to the current timeline. We need to get that merged back in. I have vague recollection of wanting to side track these changes for 2.5, but I believe they need merged into main for 3.0 now.
> 
> New PR opened to merge those tabs changes in main, then we should merge main back here. #2679

Ok we'll have to take a look at the TabsController implementation of the new RTI initialization now.  Looks like you had already anticipated this change:

```
// TODO(bennypowers): adjust to fit, in or after #2570
this.#tabindex.initItems(this._tabs, this.#element);
```
If I have the opportunity tonight to take a look at this ill push some code here otherwise first in the morning.

**Comment by zeroedin** [comment]
@nikkimk definitely double check keyboard navigation here, but things seem to be working as expected for me.

**Comment by bennypowers** [comment]
checked with @nikkimk. we'll merge this even though tests in select are failing and come back to fix those in #2677

**Pull request merged**
