### PR TITLE
style: #967: Extend line lengths in prettier to 120

### PR DESCRIPTION
**Pull request by wesruv**
### Related issue

- (#967 ) Update prettier config to extend line length to 120

### What has changed and why

Developer experience, line length was set to 80 (the default) which felt small (to me)

### Ready-for-merge Checklist

Check off items as they are completed.  Feel free to delete items if they are not applicable.

- [ ] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Browser testing passed (regression testing only).
- [ ] Repository compiles and tests pass.
- [ ] Changelog updated (not needed for documentation updates).
- [ ] Documentation (README.md, WHY.md, etc.) updated or added.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Review by castastrophe — CHANGES_REQUESTED** [review]
@wesruv I don't see any updates to the prettier config: https://prettier.io/docs/en/configuration.html

**Comment by castastrophe** [comment]
Really stoked about this update, thanks for tackling it.  Check out the label details in the PR template for which labels need to be applied.  Thanks!

**Comment by wesruv** [comment]
See my first commit, it's the only change made in that one.

**Comment by castastrophe** [comment]
Okay, thanks. I looked through the PR and was only seeing the prettier updates and missed the config file. Can you address the template and label feedback then when you’re able and I’ll branch test. Code looks good.

**Comment by wesruv** [comment]
I'm not sure what this error means? I've never run into anything like this and don't know where to start:

```
 Run actions/labeler@v22s
##[error]Input required and not supplied: repo-token
Run actions/labeler@v2
##[error]Error: Input required and not supplied: repo-token
##[error]Input required and not supplied: repo-token
```

**Comment by wesruv** [comment]
Noticed that we don't have trailing commas and that it's now the default in prettier 2.x, now noticing we are specifying: `^1.19.1`

I would like to get trailing commas in arrays and objects and such, I think it reduces human error when developing, any reason why we couldn't try upgrading to 2.0?

**Comment by wesruv** [comment]
... follow up question, should that be a different PR?

**Comment by castastrophe** [comment]
@wesruv Updating to 2.0 sounds great but I like your suggestion to handle that in another PR, that keeps them pretty scoped which is nice.  The labeler issue I can poke at - it has to do with our project's shared secret and how the workflow is utilizing it.  Happy to show you some time if you're interested but I can handle it if not.

**Comment by castastrophe** [comment]
@wesruv Ah it's because your PR is from a fork - the handles stored in the project can't be shared with a fork branch for security reasons. 🤔 Can you migrate the PR?

**Comment by wesruv** [comment]
No problemo, it's here now: https://github.com/patternfly/patternfly-elements/pull/1092

**Pull request closed without merging**
