### PR TITLE
fix(jump-links): apply aria-label to list

### LINKED ISSUE #1765: [fix] pfe-jump-links heading accessibility issue
## Description of the issue

PFE Jump Links' heading has a couple accessibility issues/concerns:

1. The heading is not announced as a part of the nav. To fix it use an `aria-labelledby` attribute on the unordered list that references the heading's ID. If there is no ID on the heading, one would need to be autogenerated.
2. The live example (see screenshot) on the [Doc's components page](https://patternflyelements.org/components/jump-links/) uses a `<p>` element, which isn't really a good suggestion. Note: the code under Usage uses an `<h4>` which is ok, though.

Also, the heading slot in the Demo page is misnamed as `pfe-jump-links-nav--heading` while the code expects simply `heading`. Probably should fix this too. [See issue 1734](https://github.com/patternfly/patternfly-elements/issues/1734).

### Impacted component(s)

- pfe-jump-links

### Steps to reproduce

1. Go to [Jump Links component page](https://patternflyelements.org/components/jump-links/)
2. Inspect code at "Page Navigation"
3. See issue where there is no `aria-labelledby`

### Expected behavior

Currently it just reads:

> `link, [Link text] list 3 items`

However, once the heading is _correctly_ referenced with `aria-labelledby` it should be announced with a screen reader on the first link that is focused, like:

> `link, [Link text] list Page navigation 3 items`

### Screenshots

image

### PR DESCRIPTION
**Pull request by bennypowers**
## <Pull request description>

Adds aria-labelledby to jump links internal list

### Related issues

- closes #1765 

### What has changed and why

- Adds aria-labelledby to jump links internal list

### Testing instructions

- [ ] *Test case 1*
  1. navigate to /components/jump-links/demo
  2. use screenreader to navigate jump-links nav
  3. list should be labelled by the slotted heading
- [ ] *Test case 2*
  1. same as case 1, but at mobile breakpoint

NOTE TO testers: in my testing using VO and FF, the header text was repeated `list STANDARD SECTION standard section 5 items`. Edgium and safari did not repeat, so i suppose that's a UA thing.

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 78 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [ ] Browser testing passed.
- [x] Changelog updated.
- [x] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by kelsS** [comment]
Hey @bennypowers, upon initial review the code looks good! I will test with a screen reader shortly and report back.

**Comment by bennypowers** [comment]
Thank you @kelsS I'll set the PR to auto-merge upon your [approval](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)

**Review by zeroedin — COMMENTED** [review]
This looks good to me as far as the code changes.  I tested a bit with mac voiceover as a screen-reader and seemed to work, but I have limited skillset there.

**Comment by kelsS** [comment]
Hey @bennypowers upon reviewing the changes I have found a lot of a11y issues. This component needs to be refactored with some a11y remediation. I have a ticket to do that and want to work on it. Should I make the changes in this PR? How should we handle a possibly major refactor for this element?

**Comment by kelsS** [comment]
@bennypowers currently the component is only functional and useful to sighted mouse users without the remediation.

**Comment by bennypowers** [comment]
Yeah this PR is the place for it. If the changes are going to be substantive let's try to plan them out a little first, so we can minimize back-and-forth in review

**Comment by kelsS** [comment]
> Thank you @kelsS I'll set the PR to auto-merge upon your [approval](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)

I am approving this PR be it looks good to me as defined. I will create issues for the things I discovered while testing this PR.

**Review by kelsS — APPROVED** [review]
LGTM

**Pull request merged**
