### PR TITLE
chore: Update build script to output detailed build failures

### PR DESCRIPTION
**Pull request by castastrophe**
The build script is failing silently and making it impossible to debug the results.  I tested adding `--stream` to the build script and it actually seems to be working a little better and at least started showing when errors were logged to the console.

My most common build error is the node-sass binding warning where Sass can't compile because node-sass expects a different version of npm.  These errors aren't showing up in the command line at all without `--stream`.  It shows lerna success messages but no compiled assets.

- [x] **Test case: Error messaging**
    1. Add an error to your Sass or JS.
    2. `npm run build <component>`
    3. The output from the build should show details about the failure.

- [x] **Test case: Node-sass binding error**
    1. If you have nvm installed: `nvm use 8` (or any version other than what your node-sass is bound to)
    2. `npm run build`
    3. The output from the build should show details about the node-sass binding error.

- [x] **Test case: Build one component**
    > npm run build pfe-cta

- [x] **Test case: Build multiple components**
    > npm run build pfe-cta pfe-card pfe-band

- [x] **Test case: Build all components**
    > npm run build

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [x] Repository compiles and tests pass.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Review by heyMP — CHANGES_REQUESTED** [review]
I don't think the process is exiting on a sass compilation.  Here is an example:

Screen Shot 2021-02-18 at 11 10 40 AM

**Comment by castastrophe** [comment]
@heyMP Yeah, that's right.  It shouldn't exit, just output the error to the logs.  It's set to continue on fail.

**Comment by castastrophe** [comment]
It wasn't even doing that without the `--stream` flag

**Review by heyMP — APPROVED** [review]
👍

**Comment by castastrophe** [comment]
Last build passed: https://github.com/patternfly/patternfly-elements/actions/runs/575927118

**Pull request merged**
