### PR TITLE
fix(button): contrast error

### LINKED ISSUE #1997: [pfe-button][pfe-cta] contrast does not pass for secondary button on "saturated"
## Description of the issue

The pfe-button component `secondary` button variant needs to be updated to provide greater contrast between the text and the background.  

## Steps to Reproduce
1. https://patternflyelements.org/components/button/demo/
2. Run this snippet:
   ```js
   document.querySelector("pfe-band:nth-of-type(2)").colorPalette = 'accent';
   ```
3. Observe color contrast error. Currently, it looks like this:
    image
4. https://patternflyelements.org/components/cta/demo/
5. Focus the `Secondary + wind variant` example on `saturated` and `darkest` cards
6. Observe color contrast errors:
    Screen Shot 2022-04-28 at 11 36 06
    Screen Shot 2022-04-28 at 11 36 11

### Impacted component(s)

- pfe-button
- pfe-cta

### PR DESCRIPTION
**Pull request by bennypowers**
- Improves colour contrast for CTA in secondary+wind variant when focused on saturated contexts
- Improves colour contrast for button in secondary variant on saturated and dark contexts

### Related issues

Closes #1997 

### What has changed and why

- Use UI accent colour for button text on saturated and dark backgrounds
- Use white for CTA text when focused on saturated in secondary+wind variant

## Notes to reviewers:
For **button**, open [current](https://patternflyelements.org/components/button/demo) and [PR preview](https://deploy-preview-2014--patternfly-elements.netlify.app/components/button/demo) in separate tabs, and run this snippet in the browser dev tools console:

```js
document.querySelector("pfe-band:nth-of-type(2)").colorPalette = 'accent';
```

Before:
Screenshot 2022-04-28 at 15-49-49 Button PatternFly Elements
After:
Screenshot 2022-04-28 at 15-49-49 Button PatternFly Elements

For **CTA**, tab to the "Secondary + wind variant" on saturated context, with `color-palette="base"` (i.e. the middle card in that row)

Before:
image

After:
image

### CODE REVIEW

**Comment by zeroedin** [comment]
> 
> For **CTA**, tab to the "Secondary + wind variant" on saturated context, with `color-palette="base"` (i.e. the middle card in that row)
> 

For the CTA screenshot examples shown vs the links given I am not seeing the lighter background color on the `Secondary + wind variant` that is depicted.  Should I be?

Current:
image


DPR 2014:
image


Localhost @ `fix/button/contrast-error`:
image


**Side Note:**
All these color combos will also need design reviewed and fixed for accessibility moving forward, which we've mentioned offline just wanted to note that again.  The secondary button definitely stands out in these screenshots as being low contrast on saturated.

**Comment by bennypowers** [comment]
To see the desired effect, you've got to focus the the element by tabbing to it, or via dev tools:

Screen Shot 2022-05-02 at 19 25 07

**Comment by coreyvickery** [comment]
@bennypowers Are you migrating `pfe-button` straight to RHDS? If so, I don't think we can touch the design until after, but we could keep this issue open until then.

**Comment by bennypowers** [comment]
Yeah let's see this until https://github.com/RedHat-UX/red-hat-design-system/issues/370
And also https://github.com/RedHat-UX/red-hat-design-system/pull/349

**Pull request closed without merging**
