### PR TITLE
fix: pfe-cta svgs removed from tab order in ie11

### PR DESCRIPTION
**Pull request by TylerMartin5**
### What has changed and why
Summarize files edited as part of this MR along with a brief description of what was changed/why.

* Added focusable="false" to svg in template for ie11. The tab order will include the svg otherwise.

### Testing instructions
Be sure to include detailed instructions on how your update can be tested by another developer.

1. Tab through ctas in ie11. If svgs are no longer receiving focus, success!

#### Browser requirements
Your component should work in all of the following environments:

- [x] Latest 2 versions of Edge
- [x] Internet Explorer 11 (should be useable, not pixel perfect)
- [x] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 60.7.2 (or latest version for Red Hat Enterprise Linux distribution)
- [x] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [x] Latest 2 versions of Safari
- [x] Galaxy S9 Firefox
- [x] iPhone X Safari
- [x] iPad Pro Safari
- [x] Pixel 3 Chrome

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did browser testing pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?
- [x] Did you update the CHANGELOG.md file with a summary of this update?

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by TylerMartin5** [comment]
hey @castastrophe - Just updated. Did I do that correctly?

**Comment by castastrophe** [comment]
@TylerMartin5 Yes, perfect!  Has this update been browser tested?

**Comment by TylerMartin5** [comment]
@castastrophe Yup! The focusable attribute is only implemented in ie and edge and is working as intended there. The others will ignore it.

**Comment by castastrophe** [comment]
@TylerMartin5 Awesome!  Can you fill out the template at the top of the comment section here and merge in the latest.  I'll 👍

**Pull request merged**
