### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by starryeyez024**
Add discovery doc link

### CODE REVIEW

**Comment by mwcz** [comment]
Is that a public link?

**Comment by castastrophe** [comment]
@mwcz Only Red Hat accounts can access the Google doc for editing, others should be able to view it though.

**Comment by castastrophe** [comment]
JK, that's not configurable.  Only Red Hatters can see this Google doc.  It's a first draft but once we get more input on the format, we can convert to a md in the repo.

**Comment by mwcz** [comment]
:+1:

**Pull request merged**
