### PR TITLE
pfe-accordion | resolves accessibility issue 444

### PR DESCRIPTION
**Pull request by starryeyez024**
"Accordion focus color could be improved for accessibility #444"

### CODE REVIEW

**Comment by starryeyez024** [comment]
@kylebuch8 how do i get a netlify link to appear here?

**Comment by kylebuch8** [comment]
@starryeyez024 The preview is now available. I just told this branch to merge master in.
https://deploy-preview-447--happy-galileo-ea79c4.netlify.com/elements/pfe-accordion/demo/

**Comment by starryeyez024** [comment]
@chrisdo1 your code LGTM; I think you can approve and merge since I opened the MR 👍

**Comment by starryeyez024** [comment]
@chrisdo1 Lester's Grandpa Tells Myths

**Pull request merged**
