### PR TITLE
docs: v1 redirect

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did
- add a redirect to netlify config, which forwards `/v1/*` to the last good [v1 docs page](https://61f9ac3d5f4a9200081bb953--patternfly-elements.netlify.app/)
- add a docs versions dropdown (will only appear on the v2 docs at the moment)

## Not done
- create a special netlify subdomain for v1 so that we can make updates to the v1 docs without having to change the redirect url

### CODE REVIEW

**Comment by brianferry** [comment]
Two things I'm seeing so far: when I go to the v1 page and I click on another component I am redirected back to the v2 of the docs.  

So for example, if I go to https://deploy-preview-2161--patternfly-elements.netlify.app/components/accordion/ and switch to the v1 site I get https://deploy-preview-2161--patternfly-elements.netlify.app/v1/components/accordion/.  Then I click on the "autocomplete" component in the sidebar I am redirected to https://deploy-preview-2161--patternfly-elements.netlify.app/components/autocomplete/ and not to https://deploy-preview-2161--patternfly-elements.netlify.app/v1/components/autocomplete/.

**Comment by brianferry** [comment]
Sorry, hit the button before adding the second lol.

The second thing is I'm not seeing the actual components loading on the v1 site probably because it's trying to load https://deploy-preview-2161--patternfly-elements.netlify.app/[resource] instead of https://61f9ac3d5f4a9200081bb953--patternfly-elements.netlify.app/[resource] like the v1 page should.

**Comment by bennypowers** [comment]
We might be able to solve that with 301 redirects on the V1 site

**Comment by bennypowers** [comment]
there's now a dropdown at https://release-v1--patternfly-elements.netlify.app, and that's the target for the dropdown on this pr. commits to the `release/v1` branch will trigger a site build for the v1 docs

**Comment by bennypowers** [comment]
The design in this PR isn't perfect, but it works. IMO we should merge and then iterate on the design in a further PR

**Comment by brianferry** [comment]
This is looking good to me, all of the links worked & it stayed on the v1 docs.  Didn't see the dropdown on the home page but not sure if it's supposed to show up there or not.  Also it looks like maybe the javascript / css isn't loading for the demos of the components but that could be something we work on like you said by pushing to that branch?

**Comment by bennypowers** [comment]
yeah we'd have to fix that on release/v1

**Comment by bennypowers** [comment]
- dropdown moved to logo bar
- versions.json added to docs/_data
- same for the v1 branch

If the dropdown doesn't look 100%, *please* let's defer that to a subsequent PR

**Review by brianferry — APPROVED** [review]

**Comment by markcaron** [comment]
Looks good enough for now. We can clean up the style a little bit once we overhaul the docs. Thanks, @bennypowers!

**Pull request merged**
