### PR TITLE
fix(tools): fix demo script import and styles

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. fix the demo page import and it's associated export map
2. replace remaining `--pfe` styles

## Testing Instructions

1. run dev server here
2. link pfe tools and run dev server in rhds

### CODE REVIEW

**Comment by zeroedin** [comment]
Pretty sure I have everything linked correctly and setup getting the following error after linking pfe-tools:

```
✗ npm run start

> @rhds/elements@1.0.0-beta.28 start
> wireit

⬆️ [watch:compile] Service started
🏃 [analyze] Running command "cem analyze"
```

Assuming the following change to package.json:

```json
"scripts": {
   ...
   "analyze": "wireit",
   ...
    "analyze": {
      "command": "npm run --if-present analyze",
      "files": [
        "elements/*/demo/*.html",
        "elements/**/*.ts",
        "elements/**/*.css"
      ],
      "output": [
        "elements/custom-elements.json"
      ]
    },
    ...
```
Which results in:

```
3:24:38 PM - Starting compilation in watch mode...


> @rhds/elements@1.0.0-beta.28 analyze
> wireit

💤 [analyze] Waiting for another process which is already running this script.
elements/rh-secondary-nav/test/fixtures.ts(1,22): error TS2307: Cannot find module '@open-wc/testing' or its corresponding type declarations.
```

**Comment by zeroedin** [comment]
> 💤 [analyze] Waiting for another process which is already running this script.
> elements/rh-secondary-nav/test/fixtures.ts(1,22): error TS2307: Cannot find module '@open-wc/testing' or its corresponding type declarations.

By moving the fixture from secondary-nav out of the `fixture.ts` which I think is problematic during build back into the main test file, this error goes away however still end up with: 

```
💤 [analyze] Waiting for another process which is already running this script.

3:29:14 PM - Found 0 errors. Watching for file changes.
```
which stops the dev-server from completing the load.  Assuming reorganization of wireit commands for RHDS are needed,

**Comment by bennypowers** [comment]
try copying the files instead of moving, or just editing the relevant lines

**Comment by zeroedin** [comment]
> try copying the files instead of moving, or just editing the relevant lines

Sorry, these comments should have been on the PR in RHDS, just realized they are in the wrong place.

**Comment by zeroedin** [comment]
> try copying the files instead of moving, or just editing the relevant lines

Copying `pfe-tools` over after being built seems to work better than the `npm link` did.  Going to run a couple more tests to validate my steps but I think this PR might be good to go.

**Review by zeroedin — APPROVED** [review]

**Pull request merged**
