### PR TITLE
docs(button): add href for Link Variant

### PR DESCRIPTION
**Pull request by tejas161**
## What I did

1.  Add example of how to include href values to pf-button link variant.

## Testing Instructions

1. Observe and Test the pf-button link variant with href value.

## Notes to Reviewers

@adamjohnson I Had some questions regarding A11y:- 

1.  When I use TAB Key and try clicking the pf-button with a href link, the Focus gets inside the button. Would that be a Accessibility concern ?

Closes: #2769

### CODE REVIEW

**Comment by adamjohnson** [comment]
> When I use TAB Key and try clicking the pf-button with a href link, the Focus gets inside the button. Would that be a Accessibility concern ?

Yes. This will fail WCAG Success Criterion [4.1.2](https://www.w3.org/WAI/WCAG22/quickref/#name-role-value) Name, Role Value — Level A.

This is a commonly seen issue most often referred to as "nested interactive controls". When an interactive control has another interactive control as a child element, it disrupts how the child element is communicated to the accessibility tree. This issue can prevent users of assistive technology from finding the child element, getting its correct name and role information, or interacting with it.

The best way forward would be to not nest interactive controls.

It looks like [Lumar](https://www.lumar.io/), a QA and accessibility tool Red Hat uses, has [a check for nested interactive controls](https://www.lumar.io/wiki/accessibility/keyboard-a/nested-interactive/).

**Comment by tejas161** [comment]
> > When I use TAB Key and try clicking the pf-button with a href link, the Focus gets inside the button. Would that be a Accessibility concern ?
> 
> Yes. This will fail WCAG Success Criterion [4.1.2](https://www.w3.org/WAI/WCAG22/quickref/#name-role-value) Name, Role Value — Level A.
> 
> This is a commonly seen issue most often referred to as "nested interactive controls". When an interactive control has another interactive control as a child element, it disrupts how the child element is communicated to the accessibility tree. This issue can prevent users of assistive technology from finding the child element, getting its correct name and role information, or interacting with it.
> 
> The best way forward would be to not nest interactive controls.
> 
> It looks like [Lumar](https://www.lumar.io/), a QA and accessibility tool Red Hat uses, has [a check for nested interactive controls](https://www.lumar.io/wiki/accessibility/keyboard-a/nested-interactive/).



> > When I use TAB Key and try clicking the pf-button with a href link, the Focus gets inside the button. Would that be a Accessibility concern ?
> 
> Yes. This will fail WCAG Success Criterion [4.1.2](https://www.w3.org/WAI/WCAG22/quickref/#name-role-value) Name, Role Value — Level A.
> 
> This is a commonly seen issue most often referred to as "nested interactive controls". When an interactive control has another interactive control as a child element, it disrupts how the child element is communicated to the accessibility tree. This issue can prevent users of assistive technology from finding the child element, getting its correct name and role information, or interacting with it.
> 
> The best way forward would be to not nest interactive controls.
> 
> It looks like [Lumar](https://www.lumar.io/), a QA and accessibility tool Red Hat uses, has [a check for nested interactive controls](https://www.lumar.io/wiki/accessibility/keyboard-a/nested-interactive/).

Thanks @adamjohnson for the information and guidance for the A11y on this issue.

Hi @bennypowers, Since I can't nest the anchor tag inside the pf-button.
Should I try creating a **href** prop for pf-button "link-variant" for adding links ? Your thoughts on this.

**Comment by bennypowers** [comment]
yeah i think changing the template for pf-button depending on whether there's an `href` attribute makes sense

@adamjohnson, considering that [pfv4 has a `<Button component="a" href={}>` component ](http://v4-archive.patternfly.org/v4/components/button/#links-as-buttons), and considering our mandate in this repo to reproduce as closely as possible upstream patterns, do you concur that we can have `<pf-button href="...">`, which would produce an anchor in shadow dom?

**Comment by adamjohnson** [comment]
@bennypowers As long as there are no nested interactive controls, that works for me. 👍

**Comment by tejas161** [comment]
Closing this PR, further changes can be tracked under PR #2814

**Pull request closed without merging**
