### PR TITLE
fix: [pfe-badge] adds dark variant

### PR DESCRIPTION
**Pull request by rmscampos**
### Related issues
[[fix] pfe-badge | adds dark variant #1772 ](https://github.com/patternfly/patternfly-elements/issues/1772)

- (#100) Description of issue

PFE-badge variants are barely visible against the background of the RHEC Search pages.

### Preview

Link(s) to demo page(s) where this element can be viewed:

- Local: [pfe-badge demo page](http://localhost:8080/elements/pfe-badge/demo/)
- Netlify: [pfe-badge demo page](https://deploy-preview-1783--patternfly-elements.netlify.app//elements/pfe-badge/demo/)

### What has changed and why

- added a "dark" variant to the pfe-badge files

### Testing instructions

- [ ] *Test case #1*
  1. Go here
  2. Do this
- [ ] *Test case #2*
  1. Go here
  2. Do this

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Internet Explorer 11 (should be useable, not pixel perfect)
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 78 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [x] Browser testing passed.
- [ ] Changelog updated.
- [x] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by kylebuch8** [comment]
@rmscampos - Thanks for sending this in. I think we want to take a different approach with this issue. Instead of adding another state, like dark, I think we need to take advantage of the context system we have with PatternFly Elements.

https://patternflyelements.org/theming/colors/#contextually-aware-content

I think what we'll end up doing is to make `pfe-badge` "contextually aware" so the default state of the badge can change its colors based on the context. We have two Sass mixins, `pfe-contexts` and `pfe-surfaces`, that helps us accomplish this without too much work.

https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-sass/mixins/_custom-properties.scss#L181
https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-sass/mixins/_custom-properties.scss#L142

We're going to get some help from the design team on some background and text colors. I've been chatting with them this morning. Once we get the colors, I can work with you to implement the context aware piece for `pfe-badge`.

**Comment by coreyvickery** [comment]
@kylebuch8 Does this still need to be reviewed? @rmscampos Can you provide a preview link? I don't think I saw one.

**Comment by rmscampos** [comment]
> @kylebuch8 Does this still need to be reviewed? @rmscampos Can you provide a preview link? I don't think I saw one.

@coreyvickery Since we're going to be working on an alternative solution, I don't think this needs to be reviewed anymore. Thanks!

**Comment by bennypowers** [comment]
Closing based on https://github.com/patternfly/patternfly-elements/pull/1783#issuecomment-931471147

Let's open a new PR against the 2.0 `main` branch if this is still relevant

**Pull request closed without merging**
