### PR TITLE
chore: fix netlify build by adding plugin-local-install-core

### PR DESCRIPTION
**Pull request by kylebuch8**
Attempting to fix the Netlify build by following the guidance here:
https://github.com/netlify/build/issues/1640

The issue with the local plugin is that the dependencies are not installed. The additional plugin should fix the issue.

### CODE REVIEW

**Review by bennypowers — APPROVED** [review]
Nice solution, @kylebuch8

**Comment by bennypowers** [comment]
So close! https://app.netlify.com/sites/patternfly-elements/deploys/634ae308fd11820008302f75

**Comment by kylebuch8** [comment]
I feel like if we just point at the actual npm package rather than using the local version, it should just work.

**Comment by bennypowers** [comment]
But we don't publish this as an npm package

**Comment by kylebuch8** [comment]
It looks like we published it 8 months ago.

https://www.npmjs.com/package/netlify-plugin-github-actions

**Comment by bennypowers** [comment]
Oh lol ok yeah sure

**Pull request merged**
