### PR TITLE
Upgrade to latest version of storybook

### PR DESCRIPTION
**Pull request by castastrophe**
A very easy upgrade for a lot of extra features and polish plus the ability to hook into storybook for automated visual regression testing.

### CODE REVIEW

**Comment by castastrophe** [comment]
@mwcz I see escape html was added to pfe-card but does it need to be added to any other storybooks?

**Comment by mwcz** [comment]
@castastrophe I'm not entirely sure.  I just tested out the branch again and I'm not seeing the same exposed HTML as before.  Everything looked good.

**Comment by castastrophe** [comment]
@kylebuch8 Is this story still blocked?  Do we want to move forward with upgrading storybook or does this need more discussion first?

**Comment by starryeyez024** [comment]
Noting that this version should add the ability to surface component markdown files in storybook

**Comment by starryeyez024** [comment]
Laughter Goes Through Me!  

:D this is awesome!

**Comment by starryeyez024** [comment]
@castastrophe when I try to run hugo in this branch I get an error:
```
ktotten@MacBook-Pro-2:~/Sites/patternfly-elements/docs$ hugo server -D
Building sites … ERROR 2019/10/01 12:02:38 Error while rendering "page" in "getting-started/": html/template:__cafd8af4347e8a8e4e896f1798a844de: ends in a non-text context: {stateJS delimNone urlPartNone jsCtxRegexp attrNone elementScript <nil>}
Total in 154 ms
Error: Error building site: logged 1 error(s)
```

**Comment by castastrophe** [comment]
@mwcz I think this is ready to merge, if it looks good to you can you approve?

**Pull request merged**
