### PR TITLE
docs: autoreveal the body on docs pages

### LINKED ISSUE #1886: `unresolved` not removed from body element in time
## Description of the issue

on docs pages, the `unresolved` attribute is not being removed until the timer runs out.

### Impacted component(s)

- docs pages

h/t @kylebuch8 for the report

### PR DESCRIPTION
**Pull request by bennypowers**
Docs pages: Reveal the body when components update

Fixes #1886

### CODE REVIEW

**Comment by brianferry** [comment]
Taking a look at the deployed code I do see the `unresolved` tag being removed in the `body` tag.  👍

**Comment by bennypowers** [comment]
@brianferry the kicker is that `[unresolved]` should be removed _after_ every pfelement on the page has updated, which I think this PR accomplishes. If you formally approve in the github UI, it will merge

**Comment by bennypowers** [comment]
Ordinarily, `[unresolved]` is remove after either:
- every pfelement updates
- 5 seconds elapses
whichever is shortest

the instigating issue is that 5 seconds elapses first

**Review by brianferry — APPROVED** [review]

**Review by kylebuch8 — APPROVED** [review]
Lovely garden. Trees majestic.

**Pull request merged**
