### PR TITLE
feat: pfe-tabs horizontal overflow scrolling 

### LINKED ISSUE #1013: pfe-tabs overflow scroll
# Component name: 

pfe-tabs

## Design specification updates

When the tab label section width is wider than the container it's in, add the ability to scroll between the tabs.

More info to come from @coreyvickery

### PR DESCRIPTION
**Pull request by kylebuch8**
Closes #1013 

## Description
Adds horizontal scrolling capabilities to horizontal tabs. This feature adds a left arrow and a right arrow when the tabs are too large for its container. This feature uses a ResizeObserver to respond to changes in the size of the component and will add the scrolling capability once the tabs are too large. This change also impacts `pfe-content-set` in that when the component renders tabs, they will have the scrolling feature if the tabs are too large.

### Related issues
#1013 

### Preview
- [Horizontal scrolling demo](https://deploy-preview-1698--patternfly-elements.netlify.app/elements/pfe-tabs/demo/horizontal-scroll.html)
- [Tabs demo](https://deploy-preview-1698--patternfly-elements.netlify.app/components/tabs/)
- [Tabs in pfe-content-set](https://deploy-preview-1698--patternfly-elements.netlify.app/elements/pfe-content-set/demo/) Scroll to the "The pfe-content-set comes with a mutation observer so that you may dynamically add headers and panels." section and continue to click the "Add Header & Panel" button until the tabs are too big for the container

### Testing instructions

- [ ] *pfe-tabs*
  1. Go to https://deploy-preview-1698--patternfly-elements.netlify.app/elements/pfe-tabs/demo/horizontal-scroll.html
  2. The first tab set should have a horizontal scroll bar
  3. Scroll all the way to the right
  4. Make sure that the right arrow on the side of the tabs is disabled and the left arrow is enabled
  5. Scroll all the way to the left
  6. Make sure the left arrow is disabled and the right arrow is enabled
  7. Scroll to the middle
  8. Make sure both the left arrow and the right arrow are enabled
  9. Scroll all the way to the left
  10. Click the right arrow
  11. Make sure that the previously hidden content is now visible
  12. Click the right arrow until it scrolls all the way to the right.
  13. Click the left arrow 
  14. Make sure the previously hidden content is now visible
  15. Click the left arrow until is scrolls all the way to the left
  16. Resize the screen and make sure that the left and right arrows are added to tab sets that are too large for the container
  17. Make the screen larger and make sure the arrows are now longer visible when the tab set is small enough to fit inside its container
- [ ] *pfe-content-set*
  1. Go to https://deploy-preview-1698--patternfly-elements.netlify.app/elements/pfe-content-set/demo/
  2. Scroll to the "The pfe-content-set comes with a mutation observer so that you may dynamically add headers and panels." section and continue to click the "Add Header & Panel" button until the tabs are too big for the container
  3. Make sure the left and right arrows appear when the tabs are too large for its container

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Internet Explorer 11 (should be useable, not pixel perfect. There should be a horiztonal scroll bar when the tabs are too large for the container)
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 78 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [ ] Browser testing passed.
- [ ] Changelog updated.
- [ ] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by kylebuch8** [comment]
@coreyvickery Can I get a design review?

**Comment by coreyvickery** [comment]
@kylebuch8 The styling looks good to me, but I'm still seeing the scroll bar. Is that still being discussed to keep or remove?

**Comment by kylebuch8** [comment]
@coreyvickery - Here's the latest with the scrollbar hidden.
https://deploy-preview-1698--patternfly-elements.netlify.app/elements/pfe-tabs/demo/horizontal-scroll.html

**Comment by kelsS** [comment]
Hey @kylebuch8 I tested the colors and they are passing with Lighthouse and WAVE. So LGTM.

**Review by kelsS — APPROVED** [review]

**Comment by kylebuch8** [comment]
Need to add the ability to scroll the active tab into view on page load if a selected-index is provided.

**Comment by bennypowers** [comment]
@kylebuch8 is this still relevant to pfe 2?

**Comment by bennypowers** [comment]
PFv4 has this feature, so we should implement it as part of tabs 1:1
https://www.patternfly.org/v4/components/tabs#default-overflow

**Comment by zeroedin** [comment]
Superseded by pfe-tabs 1:1 #2099 which includes horizontal overflow scrolling

**Pull request closed without merging**
