### PR TITLE
Remove CP theme and references to it

### PR DESCRIPTION
**Pull request by castastrophe**
This is related to issue https://github.com/patternfly/patternfly-elements/issues/287 - removing the cp-theme from the PatternFly Elements repo.  I have saved the theme in my dropbox here: https://www.dropbox.com/s/tvizylmkxx9vghf/cp-theme.zip?dl=0

### CODE REVIEW

**Comment by starryeyez024** [comment]
awesomeness!!!!
nice-to-have, would it be worth pulling in this file in the demo pages where we are removing references to CP-theme?
https://gitlab.corp.redhat.com/uxdd/redhat-theme/raw/0.4.0/dist/advanced-theme.css

**Comment by castastrophe** [comment]
Let's call that next steps.  Yes, it would be nice to be able to test the theme is working but we can't pull it from gitlab outside the VPN.

**Comment by starryeyez024** [comment]
> Let's call that next steps. Yes, it would be nice to be able to test the theme is working but we can't pull it from gitlab outside the VPN. @starryeyez024

@castastrophe  aha, something must have went sideways yesterday, some of the styles were mangled/missing, likely just a compile issue. I now see the orange & blue PFE colors, so that's totally fine. 

Leftovers: Gorgonzola, Tomato, Manacotti. 👍

**Comment by markcaron** [comment]
Sounds good.

**Pull request merged**
