### PR TITLE
fix(tools): update cem deps

### PR DESCRIPTION
**Pull request by bennypowers**
Updates dependencies

### CODE REVIEW

**Review by zeroedin — COMMENTED** [review]
LGTM.

**Comment by bennypowers** [comment]
> > custom-elements-manifest.ts:4:32 - error TS7016: Could not find a declaration file for module 'cem-plugin-readonly'. '/Users/sps/Sites/_pattern-fly/pfe2/node_modules/cem-plugin-readonly/index.js' implicitly has an 'any' type.
> > Try `npm i --save-dev @types/cem-plugin-readonly` if it exists or add a new declaration (.d.ts) file containing `declare module 'cem-plugin-readonly';`
> > 4 import { readonlyPlugin } from 'cem-plugin-readonly';
> > ~~~~~~~~~~~~~~~~~~~~~
> > Found 1 error.
> 
> On `npm ci`

I think this is my fault in cem-plugin-readonly. taking a look...

**Comment by bennypowers** [comment]
@zeroedin can you try again please (i force-pushed)

**Comment by zeroedin** [comment]
> @zeroedin can you try again please (i force-pushed)

`npm ci` now is functioning as expected.

**Review by brianferry — APPROVED** [review]
👍

**Pull request merged**
