### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by bennypowers**
Updates many dependencies

### CODE REVIEW

**Comment by zeroedin** [comment]
@bennypowers 

On fresh install when loading label demo.

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "pfe-button" has already been used with this registry
    at http://localhost:8001/node_modules/@lit/reactive-element/decorators/custom-element.js:6:80
    at http://localhost:8001/node_modules/@lit/reactive-element/decorators/custom-element.js:6:100
    at a (http://localhost:8001/elements/pfe-label/node_modules/@patternfly/pfe-button/pfe-button.js:5:42)
    at http://localhost:8001/elements/pfe-label/node_modules/@patternfly/pfe-button/pfe-button.js:42:266
```

**Comment by zeroedin** [comment]
> 
> Also primary-detail.
> 

Correction primary detail looks to be a seperate issue with the demo/pfe-primary-detail.js:

```
Error while transforming elements/pfe-primary-detail/demo/pfe-primary-detail.js: Top-level await is not available in the configured target environment ("es2020")

   5 | const root = document.querySelector('[data-demo="pfe-primary-detail"]')?.shadowRoot ?? document;
   6 |
>  7 | await Promise.all(Array.from(root.querySelectorAll('pfe-primary-detail'), x => x.updateComplete));
   8 |
   9 | root.addEventListener('change', event => {
  10 |   if (event instanceof PrimaryDetailChangeEvent) {

```

Commenting out line 7 and the demo seems to load correctly and the events seem to fire ok, not sure that line is needed.

**Comment by zeroedin** [comment]
lightdom.css also doesn't appear to be loading for the components that have it linked in their demos:

```
GET http://localhost:8000/elements/pfe-primary-detail/pfe-primary-detail--lightdom.min.css net::ERR_ABORTED 404 (Not Found)
```

```
GET http://localhost:8000/elements/pfe-card/pfe-card--lightdom.min.css net::ERR_ABORTED 404 (Not Found)
```

```
GET http://localhost:8000/elements/pfe-cta/pfe-cta--lightdom.min.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by brianferry** [comment]
Ran the tests locally and everything looked good from my end, all the components built and looked correct on their docs pages.  @zeroedin - Can you confirm whether or not clearing node_modules & running npm run clean:nuke and then reinstalling helps clear some of those issues you were seeing?  That's what I ran on mine and it built afterwards

**Comment by zeroedin** [comment]
> Ran the tests locally and everything looked good from my end, all the components built and looked correct on their docs pages. @zeroedin - Can you confirm whether or not clearing node_modules & running npm run clean:nuke and then reinstalling helps clear some of those issues you were seeing? That's what I ran on mine and it built afterwards

Yes ran it several times yesterday and just for brevity again after you asked:

Here is what pfe-label demo looks like:

Screen Shot 2022-08-19 at 3 14 40 PM

Here is the error:

image

This was after:

```
git fetch
git checkout chore/dependencies/august-2022
git reset --hard origin/chore/dependencies/august-2022
git clean -fdx
nvm use
npm ci
npm start
```

**Comment by bennypowers** [comment]
@zeroedin please check again

**Comment by zeroedin** [comment]
@bennypowers `pfe-autocomplete` also has a dependency on `pfe-button`, we should add it to it's package.json as well.  Otherwise this looks good to go.

**Comment by bennypowers** [comment]
@zeroedin let's do that in a new PR

**Review by zeroedin — APPROVED** [review]

**Pull request merged**
