### PR TITLE
removing cats from card story. sorry cats...

### PR DESCRIPTION
**Pull request by kylebuch8**

### CODE REVIEW

**Comment by starryeyez024** [comment]
No can-do, different generator please

**Comment by mwcz** [comment]
LBTM

**Comment by mwcz** [comment]
Sad-young-brown-tabby-kitten

**Comment by castastrophe** [comment]
I don't think removing all personality from a project makes it look more professional. This is an upstream design system, what's so unprofessional about generic cat photos? It's a stable photo generator site which provides very consistent images suitable for all ages.  It seems like a nice, safe choice and a tool that's been online for a long time with very little downtime.

**Pull request closed without merging**
