### PR TITLE
feat: Add event emission to pfe-cta (#741)

### LINKED ISSUE #741: Add event to pfe-cta
So that when a user clicks on a CTA or uses the enter key to make the button active state, an event should fire so that Analytics trackers can measure that action.

### PR DESCRIPTION
**Pull request by castastrophe**
Fixes #741 

### What has changed and why
Summarize files edited as part of this MR along with a brief description of what was changed/why.

* https://github.com/patternfly/patternfly-elements/issues/741
* Demo page: https://deploy-preview-761--happy-galileo-ea79c4.netlify.com/elements/pfe-cta/demo/

### Testing instructions
Be sure to include detailed instructions on how your update can be tested by another developer.

1. Automated tests should pass.
2. Click a link and ensure the console message appears on the demo page.

#### Browser requirements
Your component should work in all of the following environments:

- [x] Latest 2 versions of Edge
- [x] Internet Explorer 11 (should be useable, not pixel perfect)
- [x] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [x] Firefox 60.7.2 (or latest version for Red Hat Enterprise Linux distribution)
- [x] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [x] Latest 2 versions of Safari
- [x] Galaxy S9 Firefox
- [x] iPhone X Safari
- [x] iPad Pro Safari
- [x] Pixel 3 Chrome

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did browser testing pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?
- [x] Did you update the CHANGELOG.md file with a summary of this update?

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by castastrophe** [comment]
TODO: Work on the event emission tests.

**Comment by starryeyez024** [comment]
Tested, but not code reviewed (by me):  Lender Growth Takes Money

image

**Comment by starryeyez024** [comment]
Just noting that I still have not heard back from SDI. However we could go ahead and merge (@kylebuch8 noted he was reviewing it and it looked good) and we can modify the events if need be later.

One question @castastrophe , I don't see the cool alert thing anymore, is that still supposed to be on the [demo page](https://deploy-preview-761--happy-galileo-ea79c4.netlify.com/elements/pfe-cta/demo/)?

image

**Comment by castastrophe** [comment]
@starryeyez024 I bet it's in a commit that I haven't pushed up yet. I know I was waiting to get the thumbs up first and I think I was away from my computer when it came

**Comment by castastrophe** [comment]
@starryeyez024 I pushed everything up!  I'll take a look once the netlify finishes building - maybe this afternoon.  I have some free time between 2pm-4pm.

**Pull request merged**
