### PR TITLE
Fix bug in pfe-tab-panel

### PR DESCRIPTION
**Pull request by castastrophe**
Fixes issue #390: padding disappears on tab-panel when no variant present.

### CODE REVIEW

**Comment by starryeyez024** [comment]
@castastrophe did any of the mixins change, or just the filenames?

**Comment by chrisdo1** [comment]
@castastrophe One thing that we need is the active state for a tab without a declared variant on a dark background. 

in `pfe-tab.scss` around line 78, this works:
`:host([aria-selected="true"][on="dark"]),`

**Comment by chrisdo1** [comment]
@castastrophe Looking at this in patternkit, something changed and vertical tabs are displaying as vertical on mobile.

**Comment by chrisdo1** [comment]
> @castastrophe Looking at this in patternkit, something changed and vertical tabs are displaying as vertical on mobile.
> 
> This is in pixel 3 chrome. Seeing something similar in iPhone X Safari
> https://www.evernote.com/l/AWv5lZk5qapLXI4eMmd3U0M6fVKcqgzMxXE
> 
> It's actually in the master branch too. I think it might just be the demo.
> 
> EDIT: synced this code to `cdoherty` sandbox and the vertical tabs appear as horizontal tabs in mobile browsers:
> https://www.evernote.com/l/AWs5tx528JFECpLZFVmBvH9gYE2tTenUKlg

This has been moved to a new issue: https://github.com/patternfly/patternfly-elements/issues/400

**Comment by castastrophe** [comment]
@starryeyez024 Updated this branch a bit

**Comment by chrisdo1** [comment]
+1 Browser and branch testing

**Comment by chrisdo1** [comment]
> @castastrophe One thing that we need is the active state for a tab without a declared variant on a dark background.
> 
> in `pfe-tab.scss` around line 78, this works:
> `:host([aria-selected="true"][on="dark"]),`
> 
> The issue is that the tab color is black when you don't declare a variant. Adding that code from above, so that on a dark theme it picks up this style: ` --pfe-tabs--aux: #{pfe-color(text--on-dark)};` works. But then we would need to specify the color for earth like this:
> 
> ```
> :host([pfevariant-="earth"][aria-selected="true"][on="dark"]) {
>   --pfe-tabs--aux: #{pfe-color(text)};
> }
> ```
> 
> I tried to simplify this by using the css `:not()` pseudo-class but I couldn't get it to work.

We'll address this in a different story.

**Comment by chrisdo1** [comment]
> > @castastrophe Looking at this in patternkit, something changed and vertical tabs are displaying as vertical on mobile.
> > This is in pixel 3 chrome. Seeing something similar in iPhone X Safari
> > https://www.evernote.com/l/AWv5lZk5qapLXI4eMmd3U0M6fVKcqgzMxXE
> > It's actually in the master branch too. I think it might just be the demo.
> > EDIT: synced this code to `cdoherty` sandbox and the vertical tabs appear as horizontal tabs in mobile browsers:
> > https://www.evernote.com/l/AWs5tx528JFECpLZFVmBvH9gYE2tTenUKlg
> 
> This has been moved to a new issue: #400

Resolved

**Pull request merged**
