### PR TITLE
fix: add pfe-variant for pfe-content-set in observed attributes

### PR DESCRIPTION
**Pull request by diwanshi**
### Related issues

- (#830) pfe-content-set not observing attribute changes to pfe-variant

### Preview

Link(s) to demo page(s) where this element can be viewed:
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 

### What has changed and why

- Added pfe-variant to the list of observed attributes

### Testing instructions

Be sure to include detailed instructions on how your update can be tested by another developer.

1. 

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Internet Explorer 11 (should be useable, not pixel perfect)
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 68 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

Check off items as they are completed.  Feel free to delete items if they are not applicable.

- [ ] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [ ] Browser testing passed.
- [ ] Repository compiles and tests pass.
- [ ] Changelog updated.
- [ ] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

### CODE REVIEW

**Comment by diwanshi** [comment]
Fixes #830

**Comment by castastrophe** [comment]
@diwanshi I added the pull request template to the PR - you can find them in the `.github/PULL_REQUEST_TEMPLATE` folder.  I used `update_component.md`.  Can you add the changelog update here as well?

**Comment by castastrophe** [comment]
I think this needs an automated test added on pfe-variant to test that it is propagating correctly and prevent regressions on this for the future.  Can you add that and be sure to include testing instructions in the PR description so it can be branch tested?

**Comment by castastrophe** [comment]
@diwanshi Just bumping this feedback for when you have time.  Please let me know if you have any questions - happy to jump on a call and screen share too!

**Comment by castastrophe** [comment]
I'm going to close this out because the update to the new properties syntax will fix this

**Pull request closed without merging**
