### PR TITLE
feat(text-input): form submission

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. submit the form on enter

### CODE REVIEW

**Comment by kylebuch8** [comment]
@bennypowers Should a form still be submitted if the `required` attribute is present on `pf-text-input`?

I added this code to the demo

```
<fieldset>
  <form id="pf-form">
    <legend>Text Input</legend>
    <label for="input">Input</label>
    <pf-text-input id="input" required></pf-text-input>
  </form>
</fieldset>

<script type="module">
  import '@patternfly/elements/pf-text-input/pf-text-input.js';

  const pfForm = document.querySelector('#pf-form');
  pfForm.addEventListener('submit', event => {
    event.preventDefault();

    console.log('pf-form submitted');
  });
</script>

<link rel="stylesheet" href="demo.css">
```

What I'm seeing is that event though the `required` attribute is present on `pf-text-input`, the form is still being submitted and the validation is not being caught.

**Comment by bennypowers** [comment]
@kylebuch8 https://deploy-preview-2647--patternfly-elements.netlify.app/components/text-input/demo/form-submission/

**Comment by kylebuch8** [comment]
@bennypowers Very nice. Thanks.

**Review by kylebuch8 — APPROVED** [review]
Low-tuned Guitars Thrash Metal 🤘

**Pull request merged**
